export type MovementMode = "seated" | "standing" | "lying";
export type Position = "앉기" | "서기" | "눕기";
export type AreaCode = "HEAD" | "NECK" | "SHOULDER" | "LOW_BACK" | "HIP_PELVIS";
export type RoutineRole = "긴장 완화" | "움직임 회복" | "근육 조절";

export type Routine = {
  id: string;
  name: string;
  role: RoutineRole;
  positions: Position[];
  areas: AreaCode[];
  clusters: string[];
  dose: string;
  cue: string;
  comfort: string;
  image: string;
};

export const movements = [
  {
    id: "seated" as const,
    label: "앉아서",
    description: "",
  },
  {
    id: "standing" as const,
    label: "일어서기",
    description: "",
  },
  {
    id: "lying" as const,
    label: "눕기",
    description: "",
  },
];

export const areas: Array<{ id: AreaCode; label: string; description: string }> = [
  { id: "HEAD", label: "머리", description: "턱과 머리 주변 포함" },
  { id: "NECK", label: "목", description: "목 앞·옆·뒤를 나누지 않아요" },
  { id: "SHOULDER", label: "어깨", description: "어깨와 등 위쪽 포함" },
  { id: "LOW_BACK", label: "허리", description: "허리와 몸통 주변" },
  { id: "HIP_PELVIS", label: "골반·엉덩이", description: "골반과 고관절 주변" },
];

export const recentActions = [
  { id: "RA01", label: "오래 앉아 있었다", tag: "STATIC_SITTING", areas: ["NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "RA02", label: "모니터를 오래 봤다", tag: "SCREEN_STATIC", areas: ["HEAD", "NECK", "SHOULDER"] },
  { id: "RA03", label: "휴대폰을 내려다보는 시간이 길었다", tag: "NECK_FLEXION", areas: ["HEAD", "NECK", "SHOULDER"] },
  { id: "RA04", label: "이를 악물거나 턱에 힘을 주고 있었다", tag: "JAW_TENSION", areas: ["HEAD", "NECK"] },
  { id: "RA05", label: "운전을 오래했다", tag: "DRIVING_STATIC", areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "RA06", label: "키보드나 마우스를 오래 사용했다", tag: "UPPER_LIMB_REPEAT", areas: ["NECK", "SHOULDER"] },
  { id: "RA07", label: "팔을 앞에 뻗은 채 오래 일했다", tag: "FORWARD_REACH", areas: ["NECK", "SHOULDER"] },
  { id: "RA08", label: "팔을 머리 위로 오래 사용했다", tag: "OVERHEAD_LOAD", areas: ["NECK", "SHOULDER"] },
  { id: "RA09", label: "무거운 물건을 들거나 옮겼다", tag: "LIFT_LOAD", areas: ["SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "RA10", label: "한쪽으로 가방이나 짐을 오래 들었다", tag: "ASYMMETRIC_LOAD", areas: ["SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "RA11", label: "오래 서 있었거나 평소보다 많이 걸었다", tag: "STANDING_WALKING", areas: ["LOW_BACK", "HIP_PELVIS"] },
  { id: "RA12", label: "평소보다 운동이나 집안일을 많이 했다", tag: "NOVEL_LOAD", areas: ["SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "RA13", label: "불편한 자세로 잠을 잔 것 같다", tag: "SLEEP_POSITION", areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK"] },
  { id: "RA14", label: "긴장하거나 스트레스가 큰 상태였다", tag: "GENERAL_TENSION", areas: ["HEAD", "NECK", "SHOULDER"] },
  { id: "RA99", label: "해당 없음 / 잘 모르겠어요", tag: "NONE", areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
] as const;

export const habits = [
  { id: "HB01", label: "오래 앉아 있어도 자세를 자주 바꾸지 않는다", tag: "LOW_VARIATION", areas: ["NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "HB02", label: "다리를 꼬고 앉는 시간이 잦다", tag: "ASYMMETRIC_SIT", areas: ["LOW_BACK", "HIP_PELVIS"] },
  { id: "HB03", label: "한쪽 엉덩이에 기대어 앉는 편이다", tag: "ASYMMETRIC_SIT", areas: ["LOW_BACK", "HIP_PELVIS"] },
  { id: "HB04", label: "화면을 볼 때 머리가 어깨보다 앞으로 나오는 편이다", tag: "SCREEN_STATIC", areas: ["HEAD", "NECK", "SHOULDER"] },
  { id: "HB05", label: "앉아 있을 때 어깨와 등이 둥글게 말리는 편이다", tag: "THORACIC_FLEXION", areas: ["NECK", "SHOULDER"] },
  { id: "HB06", label: "마우스·휴대폰을 주로 한쪽 손으로 오래 쓴다", tag: "UNILATERAL_UPPER", areas: ["NECK", "SHOULDER"] },
  { id: "HB07", label: "평소 이를 악물거나 이를 가는 편이다", tag: "JAW_TENSION", areas: ["HEAD", "NECK"] },
  { id: "HB08", label: "가방을 늘 같은 쪽으로 메는 편이다", tag: "ASYMMETRIC_LOAD", areas: ["SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "HB09", label: "엎드리거나 늘 같은 방향으로 자는 편이다", tag: "SLEEP_POSITION", areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK"] },
  { id: "HB10", label: "걷기나 가벼운 운동을 거의 하지 않는다", tag: "LOW_ACTIVITY", areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
  { id: "HB99", label: "해당 없음 / 잘 모르겠어요", tag: "NONE", areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"] },
] as const;

// 질문 피로도를 줄이기 위해 큰 불편 부위마다 노출할 문항을 명시적으로 제한합니다.
// 마지막 문항은 언제나 "해당 없음"이며, 배열 순서가 화면 노출 순서입니다.
export const recentActionIdsByArea: Record<AreaCode, readonly string[]> = {
  HEAD: ["RA04", "RA02", "RA03", "RA13", "RA14", "RA99"],
  NECK: ["RA02", "RA03", "RA05", "RA06", "RA13", "RA99"],
  SHOULDER: ["RA06", "RA07", "RA08", "RA10", "RA12", "RA99"],
  LOW_BACK: ["RA01", "RA05", "RA09", "RA11", "RA13", "RA99"],
  HIP_PELVIS: ["RA01", "RA05", "RA09", "RA10", "RA11", "RA99"],
};

export const habitIdsByArea: Record<AreaCode, readonly string[]> = {
  HEAD: ["HB04", "HB07", "HB09", "HB10", "HB99"],
  NECK: ["HB01", "HB04", "HB05", "HB09", "HB99"],
  SHOULDER: ["HB01", "HB05", "HB06", "HB08", "HB99"],
  LOW_BACK: ["HB01", "HB02", "HB03", "HB09", "HB99"],
  HIP_PELVIS: ["HB01", "HB02", "HB03", "HB08", "HB99"],
};

export const routines: Routine[] = [
  {
    id: "MV001",
    name: "편안한 360도 호흡과 어깨 내려놓기",
    role: "긴장 완화",
    positions: ["앉기", "서기", "눕기"],
    areas: ["HEAD", "NECK", "SHOULDER", "LOW_BACK", "HIP_PELVIS"],
    clusters: ["GENERAL_TENSION", "JAW_TENSION"],
    dose: "느린 호흡 3회",
    cue: "들이쉴 때 배와 옆구리를 편하게 넓히고, 내쉴 때 어깨 힘을 놓아보세요.",
    comfort: "어깨에 힘이 들어가지 않는 편안한 호흡 범위에서 진행해요.",
    image: "/assets/routines/R11.webp",
  },
  {
    id: "MV002",
    name: "턱 휴식 위치 만들기",
    role: "긴장 완화",
    positions: ["앉기", "서기"],
    areas: ["HEAD", "NECK"],
    clusters: ["JAW_TENSION"],
    dose: "10초 유지 × 2",
    cue: "입술은 편하게 닿게 두고, 위아래 치아는 살짝 떨어뜨려 턱의 힘을 놓아보세요.",
    comfort: "이를 꽉 물지 않고 턱이 편안한 위치만 찾아요.",
    image: "/assets/routines/R03.webp",
  },
  {
    id: "MV003",
    name: "거울 보며 부분 턱 열기",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["HEAD"],
    clusters: ["JAW_TENSION"],
    dose: "작은 범위 5회",
    cue: "정면을 보며 턱이 한쪽으로 치우치지 않게 입을 작게 열었다 닫아요.",
    comfort: "크게 벌리지 말고 편안한 범위만 사용해요.",
    image: "/assets/routines/R03.webp",
  },
  {
    id: "MV004",
    name: "앉은 턱 당기기",
    role: "근육 조절",
    positions: ["앉기", "서기"],
    areas: ["HEAD", "NECK"],
    clusters: ["SCREEN_STATIC", "NECK_FLEXION"],
    dose: "3초 유지 × 5회",
    cue: "고개를 숙이지 않고 머리 전체를 뒤로 작게 이동했다 돌아와요.",
    comfort: "목 앞쪽에 힘이 과하게 들어가지 않는 작은 범위로 해요.",
    image: "/assets/routines/R07.webp",
  },
  {
    id: "MV005",
    name: "목 좌우 천천히 돌리기",
    role: "움직임 회복",
    positions: ["앉기", "서기"],
    areas: ["HEAD", "NECK"],
    clusters: ["DRIVING_STATIC", "SLEEP_POSITION"],
    dose: "좌우 3회",
    cue: "어깨는 정면에 둔 채 고개를 좌우로 천천히 돌려요.",
    comfort: "끝까지 밀지 않고 부드럽게 돌아가는 범위까지만 해요.",
    image: "/assets/routines/R08.webp",
  },
  {
    id: "MV006",
    name: "목 옆으로 가볍게 기울이기",
    role: "움직임 회복",
    positions: ["앉기", "서기"],
    areas: ["HEAD", "NECK"],
    clusters: ["SCREEN_STATIC", "GENERAL_TENSION"],
    dose: "좌우 3회, 3초",
    cue: "손으로 당기지 않고 귀를 어깨 쪽으로 작게 기울였다 돌아와요.",
    comfort: "어깨를 끌어내리지 않고 목이 편안한 범위에서 움직여요.",
    image: "/assets/routines/R09.webp",
  },
  {
    id: "MV007",
    name: "견갑거근 방향 목 늘리기",
    role: "움직임 회복",
    positions: ["앉기", "서기"],
    areas: ["NECK", "SHOULDER"],
    clusters: ["SCREEN_STATIC", "DRIVING_STATIC"],
    dose: "좌우 10초",
    cue: "고개를 대각선 아래로 작게 돌리고 반대쪽 어깨는 편하게 둬요.",
    comfort: "손으로 강하게 당기지 않는 작은 범위에서 멈춰요.",
    image: "/assets/routines/R10.webp",
  },
  {
    id: "MV008",
    name: "누워서 작은 고개 끄덕임",
    role: "근육 조절",
    positions: ["눕기"],
    areas: ["HEAD", "NECK"],
    clusters: ["NECK_FLEXION", "SCREEN_STATIC"],
    dose: "3초 유지 × 5회",
    cue: "편하게 누워서 ‘예’라고 하듯 아주 작게 끄덕였다 돌아와요.",
    comfort: "머리를 바닥에 세게 누르지 않는 범위에서 해요.",
    image: "/assets/routines/R07.webp",
  },
  {
    id: "MV009",
    name: "어깨 올렸다 힘 빼며 내리기",
    role: "긴장 완화",
    positions: ["앉기", "서기"],
    areas: ["HEAD", "NECK", "SHOULDER"],
    clusters: ["GENERAL_TENSION", "SCREEN_STATIC"],
    dose: "3~5회",
    cue: "어깨를 가볍게 올렸다가 숨을 내쉬며 힘을 놓고 내려요.",
    comfort: "어깨를 세게 끌어내리지 말고 자연스럽게 놓아요.",
    image: "/assets/routines/R11.webp",
  },
  {
    id: "MV010",
    name: "어깨 천천히 원 그리기",
    role: "움직임 회복",
    positions: ["앉기", "서기"],
    areas: ["NECK", "SHOULDER"],
    clusters: ["UPPER_LIMB_REPEAT", "GENERAL_TENSION"],
    dose: "앞뒤 각 3~5회",
    cue: "팔의 힘을 빼고 어깨로 작은 원을 천천히 그려요.",
    comfort: "걸리는 느낌이 없는 작은 원부터 시작해요.",
    image: "/assets/routines/R11.webp",
  },
  {
    id: "MV011",
    name: "날개뼈 모았다 풀기",
    role: "근육 조절",
    positions: ["앉기", "서기"],
    areas: ["NECK", "SHOULDER"],
    clusters: ["FORWARD_REACH", "UPPER_LIMB_REPEAT"],
    dose: "3초 유지 × 5회",
    cue: "허리를 젖히지 않고 날개뼈를 부드럽게 모았다가 풀어요.",
    comfort: "어깨를 으쓱하지 않고 등 위쪽이 편안한 범위에서 해요.",
    image: "/assets/routines/R14.webp",
  },
  {
    id: "MV012",
    name: "의자 등받이 흉추 펴기",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["NECK", "SHOULDER", "LOW_BACK"],
    clusters: ["THORACIC_FLEXION", "SCREEN_STATIC"],
    dose: "5회",
    cue: "의자 등받이를 기준으로 등 위쪽을 작게 펴고 다시 편하게 돌아와요.",
    comfort: "목과 허리를 과하게 꺾지 않는 범위에서 해요.",
    image: "/assets/routines/R16.webp",
  },
  {
    id: "MV013",
    name: "앉은 몸통 회전",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["SHOULDER", "LOW_BACK"],
    clusters: ["DRIVING_STATIC", "STATIC_SITTING"],
    dose: "좌우 3회",
    cue: "골반은 정면에 두고 가슴을 좌우로 작게 돌렸다 돌아와요.",
    comfort: "반동 없이 몸통이 부드럽게 돌아가는 범위까지만 해요.",
    image: "/assets/routines/R15.webp",
  },
  {
    id: "MV014",
    name: "앉은 고양이-소",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["SHOULDER", "LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "THORACIC_FLEXION"],
    dose: "5회",
    cue: "골반부터 등을 작게 둥글게 했다가 편안한 중립으로 돌아와요.",
    comfort: "허리를 크게 꺾지 않고 작은 왕복으로 움직여요.",
    image: "/assets/routines/R16.webp",
  },
  {
    id: "MV015",
    name: "문틀 가슴 열기",
    role: "움직임 회복",
    positions: ["서기"],
    areas: ["NECK", "SHOULDER"],
    clusters: ["FORWARD_REACH", "THORACIC_FLEXION"],
    dose: "10~20초",
    cue: "팔을 문틀에 가볍게 두고 몸을 조금 앞으로 이동해요.",
    comfort: "어깨가 편안한 팔 높이에서 몸을 조금만 움직여요.",
    image: "/assets/routines/R17.webp",
  },
  {
    id: "MV016",
    name: "한 팔 가슴 앞으로 당기기",
    role: "움직임 회복",
    positions: ["앉기", "서기"],
    areas: ["SHOULDER"],
    clusters: ["UPPER_LIMB_REPEAT", "OVERHEAD_LOAD"],
    dose: "좌우 10~20초",
    cue: "어깨를 으쓱하지 않고 한 팔을 가슴 앞으로 편하게 이동해요.",
    comfort: "팔을 세게 누르지 않고 어깨가 편안한 범위에서 멈춰요.",
    image: "/assets/routines/R23.webp",
  },
  {
    id: "MV017",
    name: "벽 타고 팔 올리기",
    role: "근육 조절",
    positions: ["서기"],
    areas: ["SHOULDER"],
    clusters: ["FORWARD_REACH", "OVERHEAD_LOAD"],
    dose: "5회",
    cue: "벽을 따라 팔을 천천히 올렸다가 같은 길로 내려와요.",
    comfort: "팔이 부드럽게 올라가는 높이까지만 사용해요.",
    image: "/assets/routines/R18.webp",
  },
  {
    id: "MV018",
    name: "벽 밀기 플러스",
    role: "근육 조절",
    positions: ["서기"],
    areas: ["SHOULDER"],
    clusters: ["FORWARD_REACH", "UPPER_LIMB_REPEAT"],
    dose: "5회",
    cue: "팔꿈치를 거의 편 채 벽을 밀어 날개뼈가 갈비뼈를 따라 움직이게 해요.",
    comfort: "손목과 어깨가 편안한 거리에서 가볍게 밀어요.",
    image: "/assets/routines/R13.webp",
  },
  {
    id: "MV019",
    name: "앉은 골반 앞뒤 기울이기",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "DRIVING_STATIC"],
    dose: "5회",
    cue: "골반을 작게 앞뒤로 굴리며 허리 모양이 자연스럽게 바뀌게 해요.",
    comfort: "허리보다 골반이 작게 움직이는 범위에서 해요.",
    image: "/assets/routines/R19.webp",
  },
  {
    id: "MV020",
    name: "천천히 앉았다 일어나기",
    role: "근육 조절",
    positions: ["서기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "LOW_ACTIVITY"],
    dose: "5회",
    cue: "발을 안정적으로 두고 의자에서 천천히 일어났다 다시 앉아요.",
    comfort: "흔들리지 않는 의자를 사용하고 편안한 속도로 움직여요.",
    image: "/assets/routines-v8/chair-rise.svg",
  },
  {
    id: "MV021",
    name: "누운 골반 기울이기",
    role: "근육 조절",
    positions: ["눕기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "LOW_ACTIVITY"],
    dose: "3초 유지 × 5회",
    cue: "무릎을 세우고 골반을 작게 굴려 허리 모양을 편안하게 바꿔요.",
    comfort: "허리를 바닥에 강하게 누르지 않는 작은 움직임으로 해요.",
    image: "/assets/routines/R19.webp",
  },
  {
    id: "MV022",
    name: "한쪽 무릎 가슴 쪽으로 당기기",
    role: "움직임 회복",
    positions: ["눕기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "DRIVING_STATIC"],
    dose: "좌우 10~20초",
    cue: "허벅지 뒤를 잡고 한쪽 무릎을 몸 쪽으로 편하게 가져와요.",
    comfort: "무릎을 직접 강하게 누르지 않고 편안한 범위에서 멈춰요.",
    image: "/assets/routines/R21.webp",
  },
  {
    id: "MV023",
    name: "누워서 무릎 좌우로 넘기기",
    role: "움직임 회복",
    positions: ["눕기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "SLEEP_POSITION"],
    dose: "좌우 5회",
    cue: "양 무릎을 세우고 어깨를 바닥에 둔 채 무릎을 좌우로 작게 옮겨요.",
    comfort: "허리가 편안한 범위에서 천천히 왕복해요.",
    image: "/assets/routines/R20.webp",
  },
  {
    id: "MV024",
    name: "네발기기 고양이-낙타",
    role: "움직임 회복",
    positions: ["눕기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "SLEEP_POSITION"],
    dose: "5회",
    cue: "손과 무릎으로 지지한 뒤 등을 천천히 둥글게 했다가 편하게 펴요.",
    comfort: "손목과 무릎이 편안한 지지에서 작은 범위로 해요.",
    image: "/assets/routines/R16.webp",
  },
  {
    id: "MV025",
    name: "버드독 준비 동작",
    role: "근육 조절",
    positions: ["눕기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["LIFT_LOAD", "LOW_ACTIVITY"],
    dose: "좌우 3회, 3초",
    cue: "네발기기에서 한쪽 다리를 작게 뻗고 골반 위치를 편하게 유지해요.",
    comfort: "몸통이 흔들리지 않는 작은 뻗기부터 시작해요.",
    image: "/assets/routines/R21.webp",
  },
  {
    id: "MV026",
    name: "앉은 4자 엉덩이 늘리기",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["HIP_PELVIS"],
    clusters: ["ASYMMETRIC_SIT", "STATIC_SITTING"],
    dose: "좌우 10~20초",
    cue: "발목을 반대 허벅지에 올리고 골반부터 조금 앞으로 기울여요.",
    comfort: "무릎을 누르지 않고 허리를 편하게 세울 수 있는 범위에서 해요.",
    image: "/assets/routines/R20.webp",
  },
  {
    id: "MV027",
    name: "서서 고관절 앞쪽 늘리기",
    role: "움직임 회복",
    positions: ["서기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "DRIVING_STATIC"],
    dose: "좌우 10~20초",
    cue: "한 발을 뒤로 두고 골반을 작게 말아 앞쪽 고관절을 편하게 열어요.",
    comfort: "지지물을 잡고 허리를 꺾지 않는 범위에서 해요.",
    image: "/assets/routines-v8/leg-back.svg",
  },
  {
    id: "MV028",
    name: "앉아서 한쪽 햄스트링 늘리기",
    role: "움직임 회복",
    positions: ["앉기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["STATIC_SITTING", "STANDING_WALKING"],
    dose: "좌우 10~20초",
    cue: "한쪽 다리를 펴고 골반부터 조금 앞으로 기울여요.",
    comfort: "허리를 둥글게 말지 않고 편안한 범위에서 멈춰요.",
    image: "/assets/routines-v8/hamstring.svg",
  },
  {
    id: "MV029",
    name: "바닥 90/90 고관절 방향 전환",
    role: "움직임 회복",
    positions: ["눕기"],
    areas: ["HIP_PELVIS"],
    clusters: ["ASYMMETRIC_SIT", "LOW_VARIATION"],
    dose: "좌우 5회",
    cue: "바닥에 앉아 양 무릎을 굽힌 뒤 손으로 지지하며 좌우로 천천히 전환해요.",
    comfort: "고관절이 편안한 범위에서 손 지지를 충분히 사용해요.",
    image: "/assets/routines-v8/hip-rotation.svg",
  },
  {
    id: "MV030",
    name: "누운 엉덩이 들기",
    role: "근육 조절",
    positions: ["눕기"],
    areas: ["LOW_BACK", "HIP_PELVIS"],
    clusters: ["LOW_ACTIVITY", "STATIC_SITTING"],
    dose: "3초 유지 × 5회",
    cue: "무릎을 세우고 엉덩이에 힘을 주며 골반을 편안한 높이까지 들어요.",
    comfort: "허리보다 엉덩이에 힘이 들어오는 높이까지만 사용해요.",
    image: "/assets/routines/R21.webp",
  },
];

type Route = {
  tags: string[];
  relax: string[];
  move: string[];
  control: string[];
  reason: string;
};

export const routes: Record<AreaCode, Route[]> = {
  HEAD: [
    { tags: ["JAW_TENSION"], relax: ["MV002", "MV001"], move: ["MV003", "MV005"], control: ["MV004", "MV011"], reason: "턱에 힘을 주고 있었다고 선택해 편안한 이완과 작은 움직임을 먼저 제안해요." },
    { tags: ["SCREEN_STATIC", "NECK_FLEXION"], relax: ["MV001", "MV009"], move: ["MV005", "MV006"], control: ["MV004", "MV011"], reason: "화면을 오래 본 상황을 바탕으로 목과 어깨를 가볍게 움직이는 순서예요." },
    { tags: ["GENERAL_TENSION"], relax: ["MV001", "MV009"], move: ["MV006", "MV005"], control: ["MV004", "MV011"], reason: "긴장이 컸다고 선택해 호흡과 목·어깨의 편안한 움직임부터 시작해요." },
    { tags: ["NONE"], relax: ["MV001", "MV002"], move: ["MV005", "MV006", "MV003"], control: ["MV004"], reason: "선택한 부위와 가능한 자세만 바탕으로 가장 단순한 기본 순서를 제안해요." },
  ],
  NECK: [
    { tags: ["SCREEN_STATIC", "NECK_FLEXION", "UPPER_LIMB_REPEAT", "FORWARD_REACH"], relax: ["MV009", "MV001"], move: ["MV005", "MV006", "MV007"], control: ["MV004", "MV011", "MV008"], reason: "오래 화면을 보거나 팔을 앞에서 쓴 상황에 맞춰 목 움직임과 지지 근육 사용을 섞었어요." },
    { tags: ["DRIVING_STATIC"], relax: ["MV009", "MV001"], move: ["MV005", "MV007"], control: ["MV011", "MV004"], reason: "운전으로 같은 자세가 길었다고 선택해 회전과 날개뼈 움직임을 함께 제안해요." },
    { tags: ["SLEEP_POSITION"], relax: ["MV001", "MV009"], move: ["MV005", "MV006"], control: ["MV004", "MV008"], reason: "불편한 수면 자세를 선택해 강한 당김 없이 작은 범위부터 시작해요." },
    { tags: ["NONE", "GENERAL_TENSION"], relax: ["MV001", "MV009"], move: ["MV005", "MV006"], control: ["MV004", "MV011", "MV008"], reason: "선택한 부위와 가능한 자세만 바탕으로 목의 기본 순서를 제안해요." },
  ],
  SHOULDER: [
    { tags: ["UPPER_LIMB_REPEAT", "FORWARD_REACH", "SCREEN_STATIC"], relax: ["MV009", "MV010"], move: ["MV012", "MV015", "MV016", "MV010"], control: ["MV011", "MV017", "MV018"], reason: "키보드·마우스나 팔을 앞에 둔 시간이 길었다고 선택해 어깨 움직임과 날개뼈 조절을 섞었어요." },
    { tags: ["OVERHEAD_LOAD"], relax: ["MV009", "MV010"], move: ["MV016", "MV012"], control: ["MV017", "MV011"], reason: "팔을 위로 오래 쓴 상황을 바탕으로 편안한 범위의 움직임부터 제안해요." },
    { tags: ["ASYMMETRIC_LOAD", "LIFT_LOAD", "NOVEL_LOAD"], relax: ["MV010", "MV009"], move: ["MV013", "MV016"], control: ["MV011", "MV018"], reason: "한쪽으로 짐을 들거나 평소보다 많이 쓴 상황에 맞춰 좌우를 부드럽게 움직이는 순서예요." },
    { tags: ["NONE", "GENERAL_TENSION", "SLEEP_POSITION"], relax: ["MV009", "MV001"], move: ["MV010", "MV012", "MV016"], control: ["MV011", "MV017", "MV018"], reason: "선택한 부위와 가능한 자세만 바탕으로 어깨의 기본 순서를 제안해요." },
  ],
  LOW_BACK: [
    { tags: ["STATIC_SITTING", "DRIVING_STATIC"], relax: ["MV001"], move: ["MV019", "MV014", "MV022", "MV023"], control: ["MV020", "MV021", "MV030", "MV019", "MV014"], reason: "오래 앉아 있었다고 선택해 골반 움직임과 가벼운 근육 사용을 함께 제안해요." },
    { tags: ["LIFT_LOAD", "NOVEL_LOAD", "ASYMMETRIC_LOAD"], relax: ["MV001"], move: ["MV013", "MV024", "MV014"], control: ["MV020", "MV025", "MV021", "MV019"], reason: "평소보다 부하가 컸다고 선택해 강한 당김보다 편안한 움직임부터 제안해요." },
    { tags: ["SLEEP_POSITION"], relax: ["MV001"], move: ["MV014", "MV023", "MV019"], control: ["MV021", "MV019", "MV020"], reason: "불편한 수면 자세를 선택해 작은 범위의 허리·골반 움직임부터 시작해요." },
    { tags: ["STANDING_WALKING"], relax: ["MV001"], move: ["MV028", "MV019", "MV027"], control: ["MV020", "MV021", "MV019"], reason: "오래 서 있거나 많이 걸었다고 선택해 허리와 골반을 편하게 움직이는 순서예요." },
    { tags: ["NONE"], relax: ["MV001"], move: ["MV019", "MV014", "MV023"], control: ["MV020", "MV021", "MV019"], reason: "선택한 부위와 가능한 자세만 바탕으로 허리의 기본 순서를 제안해요." },
  ],
  HIP_PELVIS: [
    { tags: ["STATIC_SITTING", "ASYMMETRIC_SIT"], relax: ["MV001"], move: ["MV019", "MV026", "MV029"], control: ["MV020", "MV030", "MV021", "MV014"], reason: "오래 앉은 상황을 바탕으로 골반 움직임과 엉덩이 사용을 섞었어요." },
    { tags: ["DRIVING_STATIC"], relax: ["MV001"], move: ["MV026", "MV027", "MV019"], control: ["MV020", "MV030", "MV021", "MV014"], reason: "운전으로 앉은 시간이 길었다고 선택해 고관절을 편안히 움직이는 순서예요." },
    { tags: ["STANDING_WALKING"], relax: ["MV001"], move: ["MV027", "MV028", "MV029"], control: ["MV020", "MV030", "MV021", "MV014"], reason: "오래 서 있거나 많이 걸었다고 선택해 앞뒤 허벅지 움직임과 엉덩이 사용을 섞었어요." },
    { tags: ["LIFT_LOAD", "NOVEL_LOAD", "ASYMMETRIC_LOAD"], relax: ["MV001"], move: ["MV019", "MV027", "MV028"], control: ["MV020", "MV025", "MV030", "MV014"], reason: "평소보다 많이 움직인 상황에 맞춰 골반 움직임과 가벼운 근육 사용을 연결했어요." },
    { tags: ["NONE"], relax: ["MV001"], move: ["MV019", "MV026", "MV029"], control: ["MV020", "MV030", "MV021", "MV014"], reason: "선택한 부위와 가능한 자세만 바탕으로 골반·엉덩이의 기본 순서를 제안해요." },
  ],
};

export const tierLabels = {
  guest: "비회원",
  member: "일반 회원",
  lifetime: "평생 회원",
  admin: "관리자",
} as const;

export const allowedPositions: Record<MovementMode, Position[]> = {
  seated: ["앉기"],
  standing: ["앉기", "서기"],
  lying: ["앉기", "서기", "눕기"],
};

export const getRoutine = (id: string) => routines.find((routine) => routine.id === id);
